version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - azurite
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    command: "azurite --tableHost 127.0.0.1 --tablePort 10002"
    ports:
      - "10002:10002"
    volumes:
      - azurite:/Users/piotr/tmp

volumes:
  azurite: 
