services:
  web:
    build: 
      context: .
      ## dockerfile:
    networks:
      - cfrog-network
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Azure:Storage:ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://host.docker.internal:10012/devstoreaccount1;
    depends_on:
      - azurite
        
  azurite:
    networks:
      - cfrog-network
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: azurite -l /Users/piotr/Github/cfrog -d /Users/piotr/Github/cfrog/debug.log --tableHost 0.0.0.0
    ports:
      - "10012:10002"
    volumes:
      - azurite-data:/Users/piotr/Github/cfrog

networks:
  cfrog-network:
    driver: bridge

volumes:
  azurite-data:
