services:
  web:
    build: 
      context: .
      ## dockerfile:
    networks:
      - cfrog-network
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Azure:Storage:ConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;
    depends_on:
      - azurite
        
  azurite:
    networks:
      - cfrog-network
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --tablePort 9999 --tableHost 0.0.0.0 --tableKeepAliveTimeout 5 --loose --skipApiVersionCheck --disableProductStyleUrl --disableTelemetry -l /azurite-workspace -d /azurite-workspace/debug.log"
    ports:
      - "9999:9999"
    volumes:
      - azurite-data:/azurite-workspace

networks:
  cfrog-network:
    driver: bridge

volumes:
  azurite-data:
